# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: cs
pipeline:
  - name: WhitespaceTokenizer
  - name: fasttext_featurizer.FasttextFeaturizer
  - name: DIETClassifier
    number_of_transformer_layers: 0
    hidden_layer_sizes:
      text: []
    weight_sparsity: 0
    intent_clasification: True
    use_masked_language_model: False
    BILOU_Flag: False
    entity_recognition: False
    epochs: 1
  #- name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 1
  - name: MappingPolicy
